version: '3.8'

services:
  bot_service:
    build:
      context: ./bot
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - APP_URL=http://213.173.108.102
    volumes:
      - ./logs:/logs
      - ./user_data.db:/app/user_data.db
    depends_on:
      - flask_service

  flask_service:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models  # Монтируем директорию с моделями
