# docker-compose.yml

version: '3.8'

services:
  flask_service:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - APP_URL=http://213.173.108.102:8000
    depends_on:
      - bot_service

  bot_service:
    build:
      context: ./bot
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - APP_URL=http://213.173.108.102:8000
      - PAYMENT_AMOUNT=${PAYMENT_AMOUNT}
      - TON_WALLET=${TON_WALLET}
    volumes:
      - ./logs:/logs
      - ./user_data.db:/app/user_data.db
    depends_on:
      - flask_service
