name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Сборка и загрузка образа для приложения (app)
    - name: Build and push App Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./app
        file: ./app/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/eos-app:latest,${{ secrets.DOCKER_USERNAME }}/eos-app:v1.0.0

    # Сборка и загрузка образа для бота (bot)
    - name: Build and push Bot Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./bot
        file: ./bot/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/eos-bot:latest,${{ secrets.DOCKER_USERNAME }}/eos-bot:v1.0.0
